version: "2"

services:
  http-proxy:
    build: ./src
    user: root
    command: bash -c "./launch.sh"
    volumes:
      - ./logs:/var/log/erss
      - ./src/my_proxy:/code
    ports:
      - "12345:12345"
    tty: true

volumes:
  data-volume:
